# Generated by Django 6.0.3 on 2026-03-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiqindiXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('plastik', 'Plastik'), ('qurilish', 'Qurilish chiqindisi'), ('maishiy', 'Maishiy chiqindi'), ('kimyoviy', 'Kimyoviy chiqindi'), ('noaniq', 'Noaniq')], default='noaniq', max_length=20)),
                ('xavflilik', models.CharField(choices=[('past', 'Past'), ('orta', "O'rta"), ('yuqori', 'Yuqori')], default='past', max_length=10)),
                ('hajm', models.CharField(choices=[('kichik', 'Kichik'), ('orta', "O'rta"), ('katta', 'Katta')], default='orta', max_length=10)),
                ('tavsif', models.TextField(blank=True)),
                ('latitude', models.FloatField(default=41.2995)),
                ('longitude', models.FloatField(default=69.2401)),
                ('holati', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('qabul', 'Qabul qilindi'), ('rad', 'Rad etildi'), ('tasdiqlandi', 'Tasdiqlandi'), ('tozalandi', 'Tozalandi')], default='kutilmoqda', max_length=20)),
                ('ball', models.IntegerField(default=0)),
                ('ai_tahlil', models.TextField(blank=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tozalangan_sana', models.DateTimeField(blank=True, null=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='FoydalanuvchiProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_ball', models.IntegerField(default=0)),
                ('xabarlar_soni', models.IntegerField(default=0)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jami_ball'],
            },
        ),
        migrations.CreateModel(
            name='XabarRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='chiqindilar/%Y/%m/')),
                ('ai_tahlil', models.TextField(blank=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('xabar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='ekology.chiqindixabar')),
            ],
            options={
                'ordering': ['tartib'],
            },
        ),
    ]
